#!/usr/bin/env bash
set -euo pipefail

find_one() {
  local name="$1"
  local path
  path="$(find "$PWD" -type f -name "$name" -print -quit)"
  test -n "$path" || {
    echo "resource not found: $name" >&2
    exit 2
  }
  printf '%s\n' "$path"
}

TASK_SCRIPT="$(find_one business_risk_task.sh)"
SQL_RUNNER="$(find_one business_risk_sql_task.sh)"
COMMON_SCRIPT="$(find_one risk_report_common.sh)"
test -r "$COMMON_SCRIPT"

export SR_MYSQL_SSL_CA="$(find_one starrocks-ca.pem)"
export MYSQL_SSL_CA="$(find_one api-mysql-ca.pem)"

export AS_OF_TIME='${AS_OF_TIME}'
export WINDOW_START='${WINDOW_START}'
export WINDOW_END='${WINDOW_END}'

export BUSINESS_RISK_LOOKBACK_DAYS='${BUSINESS_RISK_LOOKBACK_DAYS}'
export BUSINESS_RISK_SNAPSHOT_RETENTION_DAYS='${BUSINESS_RISK_SNAPSHOT_RETENTION_DAYS}'
export BUSINESS_RISK_SOURCE_DATABASE='${BUSINESS_RISK_SOURCE_DATABASE}'
export BUSINESS_RISK_TARGET_DATABASE='${BUSINESS_RISK_TARGET_DATABASE}'
export BUSINESS_RISK_SOURCE_BET01='${BUSINESS_RISK_SOURCE_BET01}'
export BUSINESS_RISK_SOURCE_BET02='${BUSINESS_RISK_SOURCE_BET02}'

export BUSINESS_RISK_LATE_SUB_ROUND_MIN='${BUSINESS_RISK_LATE_SUB_ROUND_MIN}'
export BUSINESS_RISK_LATE_ORDER_RATE_MIN='${BUSINESS_RISK_LATE_ORDER_RATE_MIN}'
export BUSINESS_RISK_LATE_ORDER_COUNT_MIN_EXCLUSIVE='${BUSINESS_RISK_LATE_ORDER_COUNT_MIN_EXCLUSIVE}'
export BUSINESS_RISK_SAME_ROUND_COUNT_MIN='${BUSINESS_RISK_SAME_ROUND_COUNT_MIN}'
export BUSINESS_RISK_SAME_RATE_MIN='${BUSINESS_RISK_SAME_RATE_MIN}'
export BUSINESS_RISK_OPPOSITE_RATE_MIN='${BUSINESS_RISK_OPPOSITE_RATE_MIN}'
export BUSINESS_RISK_PLAYER_DEALER_WIN_RATE_MIN_EXCLUSIVE='${BUSINESS_RISK_PLAYER_DEALER_WIN_RATE_MIN_EXCLUSIVE}'
export BUSINESS_RISK_PLAYER_DEALER_ORDER_COUNT_MIN_EXCLUSIVE='${BUSINESS_RISK_PLAYER_DEALER_ORDER_COUNT_MIN_EXCLUSIVE}'

bash "$TASK_SCRIPT" validate-starrocks
