setwd("C:/Users/engry/Documents/GitHub/basic-data-analytical-lab/风控案例/a168风控与客户分析评分体系")
suppressPackageStartupMessages({library(data.table); library(yaml)})
source("函数/registry_loader.R"); source("函数/glossary_engine.R")
source("函数/rule_registry_loader.R"); source("函数/typology_report_engine.R")
tr_apply_config(); REG <- registry_load()
M <- tr_lineage_manifest(REG)
print(M[, .(角色, 版本, 字节, 行数, 换行, BOM, MD5 = substr(MD5,1,12), 在位)])
cat("\n"); print(tr_lineage_gate(REG))
cat("\n未取到版本者：", paste(M[is.na(版本), 角色], collapse=" · "), "\n")
cat("不在位者：", paste(M[在位 != "✓", 角色], collapse=" · "), "\n")
