starrocks.fe.http.url=ip-172-31-89-204.ap-northeast-1.compute.internal:8030
starrocks.fe.jdbc.url=jdbc:mysql://ip-172-31-89-204.ap-northeast-1.compute.internal:9030
starrocks.table.identifier=wm_live_risk.user_info
starrocks.user=risk
starrocks.password=REPLACE_AFTER_ROTATING_CREDENTIAL
