SELECT
    TABLE_NAME,
    COLUMN_NAME,
    COLUMN_COMMENT
FROM information_schema.columns
WHERE TABLE_SCHEMA = 'ods_mariadb_2b'
AND (
       LOWER(COLUMN_NAME) LIKE '%bet%'
    OR LOWER(COLUMN_NAME) LIKE '%user%'
    OR LOWER(COLUMN_NAME) LIKE '%member%'
    OR LOWER(COLUMN_NAME) LIKE '%account%'
    OR LOWER(COLUMN_NAME) LIKE '%wallet%'
    OR LOWER(COLUMN_NAME) LIKE '%ip%'
    OR LOWER(COLUMN_NAME) LIKE '%device%'
    OR LOWER(COLUMN_NAME) LIKE '%login%'
    OR LOWER(COLUMN_NAME) LIKE '%deposit%'
    OR LOWER(COLUMN_NAME) LIKE '%withdraw%'
    OR LOWER(COLUMN_NAME) LIKE '%bonus%'
    OR LOWER(COLUMN_NAME) LIKE '%rebate%'
    OR LOWER(COLUMN_NAME) LIKE '%commission%'
    OR LOWER(COLUMN_NAME) LIKE '%agent%'
)
ORDER BY TABLE_NAME, ORDINAL_POSITION;
