options(warn = 1, width = 220)
proj <- "C:/Users/engry/Documents/GitHub/basic-data-analytical-lab/风控案例/a168风控与客户分析评分体系"; setwd(proj)
suppressPackageStartupMessages(library(data.table))
sec <- function(t) cat("\n==================== ", t, " ====================\n", sep = "")
sec("PI01 by verdict group: economic magnitudes")
p1 <- fread("数据表/PI01_treatment_delta_member.csv", encoding = "UTF-8")
p1[, grp := fifelse(grepl("NO_EXPOSURE", verdict_exposure), "NO_EXPOSURE", fifelse(grepl("NO_BASELINE", verdict_exposure), "NO_BASELINE", fifelse(grepl("下降", verdict_exposure), "GGR_DOWN", "GGR_UP_FLAT")))]
print(p1[, .(n=.N, sum_stake_pre=round(sum(stake_pre)), sum_stake_post=round(sum(stake_post)), ggr_pre=round(-sum(stake_pre*roi_pre,na.rm=TRUE)), ggr_post=round(-sum(stake_post*roi_post,na.rm=TRUE)), sum_d_revenue=round(sum(d_revenue,na.rm=TRUE)), pooled_hold_pre_pct=round(-100*sum(stake_pre*roi_pre,na.rm=TRUE)/sum(stake_pre),3), pooled_hold_post_pct=round(-100*sum(stake_post*roi_post,na.rm=TRUE)/pmax(sum(stake_post),1),3)), by=.(treat_field, grp)][order(treat_field, grp)])
cat("\nTOTAL: ggr_pre =", round(-sum(p1$stake_pre*p1$roi_pre,na.rm=TRUE)), " ggr_post =", round(-sum(p1$stake_post*p1$roi_post,na.rm=TRUE)), " Σd_revenue =", round(sum(p1$d_revenue,na.rm=TRUE)), "\n")
cat("NO_EXPOSURE 96 members: stake_pre sum =", round(sum(p1[grp=="NO_EXPOSURE", stake_pre])), " their pre-hold pooled % =", round(-100*sum(p1[grp=="NO_EXPOSURE", stake_pre*roi_pre],na.rm=TRUE)/sum(p1[grp=="NO_EXPOSURE", stake_pre]),3), " (business lost after treatment: n_pre bets =", sum(p1[grp=="NO_EXPOSURE", n_pre]), ")\n")
cat("days pre/post medians:", median(p1$d_pre), median(p1$d_post), "\n")
sec("TL11_treatment_episode summary (fixed)")
t11 <- fread("数据表/TL11_treatment_episode.csv", encoding = "UTF-8")
print(t11[, .(n=.N, censored=sum(as.integer(censored)==1L), dur_med=as.numeric(median(duration_days,na.rm=TRUE)), bets_in_window_med=as.numeric(median(n_bets_in_window,na.rm=TRUE)), release_known=sum(!is.na(release_date))), by = .(enforcement_type, is_baccarat_member)][order(-n)])
print(t11[, .N, by = censor_reason][order(-N)])
sec("TL10_treatment_ledger")
t10 <- fread("数据表/TL10_treatment_ledger.csv", encoding = "UTF-8")
cat("rows:", nrow(t10), " members:", uniqueN(t10$member_id), "\n"); print(t10[, .N, by = .(action_class, field_name, is_baccarat_member)][order(-N)][1:15])
print(t10[, .N, by = .(field_name, value_before, value_after)][order(-N)][1:12])
sec("EV02_member_disposal event_type / action")
e2 <- fread("数据表/EV02_member_disposal.csv", encoding = "UTF-8", select = c("event_type","action","type_code","is_batch"))
cat("rows:", nrow(e2), "\n"); print(e2[, .N, by = .(event_type, action)][order(-N)][1:12])
sec("TL03b_pseudo_treatment")
t3 <- fread("数据表/TL03b_pseudo_treatment.csv", encoding = "UTF-8"); print(t3[, .N, by = .(action_type, direction)][order(-N)])
sec("TL14 x PI01 overlap")
t14 <- fread("数据表/TL14_limit_treatment.csv", encoding = "UTF-8")
cat("TL14 members:", uniqueN(t14$member_id), " in PI01:", uniqueN(intersect(t14$member_id, p1$member_id)), "\n")
sec("DONE")
