options(warn = 1, width = 220)
proj <- "C:/Users/engry/Documents/GitHub/basic-data-analytical-lab/风控案例/a168风控与客户分析评分体系"; setwd(proj)
suppressPackageStartupMessages(library(data.table))
sec <- function(t) cat("\n==================== ", t, " ====================\n", sep = "")
q <- function(x) round(quantile(x, c(.1,.25,.5,.75,.9), na.rm = TRUE), 4)
sec("PI01_treatment_delta_member (member-level pre/post)")
p1 <- fread("数据表/PI01_treatment_delta_member.csv", encoding = "UTF-8")
cat("rows:", nrow(p1), " members:", uniqueN(p1$member_id), "\n")
print(p1[, .N, by = treat_field][order(-N)])
print(p1[, .N, by = verdict_exposure][order(-N)])
num <- c("stake_pre","stake_post","d_stake","d_validbet","d_revenue","hold_pre_pct","hold_post_pct","d_hold_pct","roi_pre","roi_post","d_roi","n_pre","n_post","d_pre","d_post")
for (c in num) cat(sprintf("%-14s n=%4d  mean=%12.4f  P10..P90: %s\n", c, sum(!is.na(p1[[c]])), mean(p1[[c]], na.rm=TRUE), paste(q(p1[[c]]), collapse=" | ")))
cat("\nΣ d_revenue (platform GGR change post-pre, member-level sum):", format(sum(p1$d_revenue, na.rm=TRUE), big.mark=","), "\n")
cat("Σ stake_pre:", format(sum(p1$stake_pre,na.rm=TRUE), big.mark=","), " Σ stake_post:", format(sum(p1$stake_post,na.rm=TRUE), big.mark=","), "\n")
cat("sign test d_hold_pct > 0 :", sum(p1$d_hold_pct > 0, na.rm=TRUE), "/", sum(!is.na(p1$d_hold_pct)), " p=", signif(binom.test(sum(p1$d_hold_pct > 0, na.rm=TRUE), sum(!is.na(p1$d_hold_pct)))$p.value,3), "\n")
cat("sign test d_stake < 0 :", sum(p1$d_stake < 0, na.rm=TRUE), "/", sum(!is.na(p1$d_stake)), "\n")
cat("by treat_field: median d_hold_pct / d_stake / d_revenue\n"); print(p1[, .(n=.N, med_d_hold=round(median(d_hold_pct,na.rm=TRUE),3), med_d_stake=round(median(d_stake,na.rm=TRUE),0), sum_d_rev=round(sum(d_revenue,na.rm=TRUE),0), pooled_hold_pre=round(-100*sum(stake_pre*roi_pre,na.rm=TRUE)/sum(stake_pre,na.rm=TRUE),3), pooled_hold_post=round(-100*sum(stake_post*roi_post,na.rm=TRUE)/sum(stake_post,na.rm=TRUE),3)), by=treat_field][order(-n)])
sec("PI02_treatment_delta_platform (cohort × phase)")
p2 <- fread("数据表/PI02_treatment_delta_platform.csv", encoding = "UTF-8")
print(p2[, .(cohort, phase, n_members, n_dates, sum_stake, sum_validbet, sum_revenue, hold_pct, revenue_per_member, share_of_stake_pct, share_of_revenue_pct)])
sec("TL14_limit_treatment (limit tightening)")
t14 <- fread("数据表/TL14_limit_treatment.csv", encoding = "UTF-8")
cat("rows:", nrow(t14), " members:", uniqueN(t14$member_id), "\n"); print(t14[, .N, by = .(direction, is_baccarat_member)])
t14[, ratio := max_hi_after / max_hi_before]; cat("max_hi before P10..P90:", paste(q(t14$max_hi_before), collapse=" | "), "\n"); cat("after/before ratio P10..P90:", paste(q(t14$ratio), collapse=" | "), "\n")
print(t14[, .N, by = .(operator_lv)][order(operator_lv)])
sec("TL11_treatment_episode")
t11 <- fread("数据表/TL11_treatment_episode.csv", encoding = "UTF-8")
cat("rows:", nrow(t11), " members:", uniqueN(t11$member_id), "\n"); print(t11[, .N, by = .(enforcement_type, is_baccarat_member)][order(-N)])
print(t11[, .(n=.N, censored=sum(censored==1), dur_med=median(duration_days,na.rm=TRUE), bets_in_window_med=median(n_bets_in_window,na.rm=TRUE)), by = enforcement_type])
sec("TL10_treatment_ledger")
t10 <- fread("数据表/TL10_treatment_ledger.csv", encoding = "UTF-8")
cat("rows:", nrow(t10), " members:", uniqueN(t10$member_id), "\n"); print(t10[, .N, by = .(action_class, field_name, is_baccarat_member)][order(-N)][1:15])
sec("EV02_member_disposal event_type / action")
e2 <- fread("数据表/EV02_member_disposal.csv", encoding = "UTF-8", select = c("event_type","action","type_code","is_batch"))
cat("rows:", nrow(e2), "\n"); print(e2[, .N, by = .(event_type, action)][order(-N)][1:12])
sec("TL03b_pseudo_treatment")
t3 <- fread("数据表/TL03b_pseudo_treatment.csv", encoding = "UTF-8"); print(t3[, .N, by = .(action_type, direction)][order(-N)])
sec("DONE")
